return {
  "williamboman/mason.nvim",
  "williamboman/mason-lspconfig.nvim",
  "neovim/nvim-lspconfig",
  opts = {
    ensure_installed = {
      "ansible-language-server",
      "markdown-toc",
      "lua_ls",
      "bashls",
      "black",
      "docker_compose_language_service",
      "dockerls",
      "gopls",
      "helm_ls",
      "jsonls",
      "jqls",
      "marksman",
      "pyright",
      "svelte",
      "terraformls",
      "tflint",
      "yamlls",
      "sqlls",
      "sqls",
      "sql-formatter",
      "buf",
      "gotests",
      "golines",
      "ast-grep",
      "gospel",
    },
  },
}
